uint16 NOTSET    = 0
uint16 UNKNOWN   = 255
uint16 OFF       = 1
uint16 ON        = 2
# Color keys
uint16 RED       = 10
uint16 GREEN     = 11
uint16 YELLOW    = 12
uint16 BLUE      = 13
# Arrow & Navigation keys
uint16 OK        = 20
uint16 UP        = 21
uint16 DOWN      = 22
uint16 LEFT      = 23
uint16 RIGHT     = 24 
uint16 MENU      = 25
uint16 INFO      = 26
uint16 BACK      = 27
# Multimedia keys
uint16 PLAY      = 40
uint16 STOP      = 41
uint16 PAUSE     = 42
uint16 FAST_FWD  = 43
uint16 REWIND    = 44
uint16 EJECT     = 45
uint16 RECORD    = 46
uint16 MUTE      = 47
uint16 WINDOWS   = 48
uint16 VOL_PLUS  = 50
uint16 VOL_MINUS = 51
uint16 CH_PLUS   = 52
uint16 CH_MINUS  = 53
# Numeric keys
uint16 NUM_0     = 100
uint16 NUM_1     = 101
uint16 NUM_2     = 102
uint16 NUM_3     = 103
uint16 NUM_4     = 104
uint16 NUM_5     = 105
uint16 NUM_6     = 106
uint16 NUM_7     = 107
uint16 NUM_8     = 108
uint16 NUM_9     = 109
uint16 NUM_ENTER = 120
uint16 NUM_CLEAR = 121

uint16 key
