#!/bin/bash

# Convenience script for uploading arduino firmware.
# Usage: 
# $ rosrun pet_mk_iv_arduino_aux upload_firmware

# Example workflow:
# <Write smart code>
# $ cd ~/ros_ws
# $ catkin build
# $ rosrun pet_mk_iv_arduino_aux upload_firmware

catkin build --no-deps pet_mk_iv_arduino_aux --make-args pet_mk_iv_arduino_aux_firmware_arduino-upload