#!/bin/bash

# Convenience script for uploading arduino firmware.
# Usage: 
# $ rosrun pet_mk_iv_arduino upload_firmware

# Example workflow:
# <Write smart code>
# $ cd ~/ros_ws
# $ catkin build
# $ rosrun pet_mk_iv_arduino upload_firmware

catkin build --no-deps pet_mk_iv_arduino --make-args pet_mk_iv_arduino_firmware_hello-upload