<?xml version='1.0'?>
<!--
  \licens       Software License Agreement (MIT)
  \file         <workspace>/src/pet_mk_iv_description/urdf/pet_mk_iv.urdf.xacro
  \authors      stefan.kull@gmail.com (Github ID 'SeniorKullken')
  \repository   https://github.com/kullken/Pet-Mk-IV
  \repository   https://github.com/kullken/pet_mcu_base
  \copyright    
  \description  Main rover/robot/vehicle description.
  \usage        $ roslaunch rover_gazebo gazebo_world.launch
  \usage        $ roslaunch pet_mk_iv_description rviz.launch
  
  Xacro common info:
    The entirety of the code below is reproduced whenever the macro is called.
    We use 'params' to add additional arguments to the macro call, 
    which can be simple parameters, or entire code blocks.

  \reference http://wiki.ros.org/xacro
  \reference http://wiki.ros.org/urdf/XML/robot
  \reference http://sdformat.org/
-->

<robot name="Pet Mk.IV" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find pet_mk_iv_description)/urdf/materials.xacro"/>    <!-- Import Rviz colors -->
  <xacro:include filename="$(find pet_mk_iv_description)/urdf/pet_mk_iv_gazebo.urdf.xacro" />
  <xacro:include filename="$(find pet_mk_iv_description)/urdf/sensor_hc_sr04_sonarRange.urdf.xacro"/>
  <xacro:include filename="$(find pet_mk_iv_description)/urdf/sensor_RPi_cameraV2.urdf.xacro"/>
  <xacro:include filename="$(find pet_mk_iv_description)/urdf/sensor_mpu6050_imu.urdf.xacro"/>
  <xacro:include filename="$(find pet_mk_iv_description)/urdf/sensor_fc_123_lineDetector.urdf.xacro"/>
  <xacro:include filename="$(find pet_mk_iv_description)/urdf/chassis_zumo.urdf.xacro"/>
  <xacro:include filename="$(find pet_mk_iv_description)/urdf/wheel.urdf.xacro"/>
  <xacro:include filename="$(find pet_mk_iv_description)/urdf/visual_raspberryPi3B_sbc.urdf.xacro"/>

  <xacro:property name="robot_weight"    value="0.9"/>    <!-- unit kg  -->
  <xacro:property name="sonar_center_height" value="0.060"/>   <!-- unit m  -->
  <xacro:property name="PI"              value="3.14159265359"/>   <!-- unit n/a  -->

  <xacro:property name="chassis_height"  value="0.020"/>   <!-- unit m  -->

<!-- 
  Future implementation... Not used yet!
  <xacro:property name="chassis_dist_ground_top"   value="0.028"/>  
  <xacro:property name="chassis_ground_clearance" value="0.006"/>   
-->
  <xacro:property name="body_length" value="0.175"/>    <!-- unit m  -->
  <xacro:property name="body_width" value="0.100"/>     <!-- unit m  -->
  <xacro:property name="body_height" value="0.060"/>     <!-- unit m  -->

  <xacro:property name="body_thicknes_upper_deck" value="0.020"/>  <!-- Only used by simplified collision box-->
  <xacro:property name="body_height_upper_deck"   value="0.060"/>  <!-- Only used by simplified collision box-->
  <xacro:property name="body_thicknes_lower_deck" value="0.030"/>  <!-- Only used by simplified collision box-->
  <xacro:property name="body_height_lower_deck"   value="${body_thicknes_lower_deck/2}"/> <!-- Only used by simplified collision box-->
    
<!-- 
  Strange behaviour with Gazebo & RViz colors...
  <xacro:property name="body_gazebo_color" value="Gazebo/Brown"/> 
-->

  <xacro:property name="wheel_diameter" value="0.038"/>        <!-- unit m -->
  <xacro:property name="wheel_width" value="0.018"/>           <!-- unit m -->
  <xacro:property name="wheel_axis_distance" value="0.048"/>   <!-- unit m  -->
  <xacro:property name="wheel_axis_width" value="0.085"/>      <!-- unit m  -->

  <!--
    Robot Chassis (Pololu Zumo in a very simplified design)
    'base_link' is the 'groud zero' of the rover/robot.
    Sometimes called 'base_footprint', but we call it 'base_link'
  -->
  <xacro:chassis_zumo name="base_link" />


  <!-- Robot Inertials: Creates link + joint vs."base_link" -->
  <link name='base_link_inertial'>
    <pose>0 0 0 0 0 0</pose>
    <inertial>
      <mass value="${robot_weight}"/>
      <origin xyz="0.0 0 0.0" rpy=" 0 0 0"/>
      <inertia
          ixx="0.007" 
          ixy="-2.0E-08" 
          ixz="0.000014"
          iyy="0.0007" 
          iyz="4.6E-09"
          izz="0.0011"/>
<!-- froom Tianbot-Mini
          ixx="6.9553958488565E-04"
          ixy="-1.99945013904458E-08"
          ixz="1.43938674591944E-05"
          iyy="7.30544716315262E-04"
          iyz="4.63385578966379E-09"
          izz="0.0011040368246549"
-->
    </inertial>
  </link>

  <joint name='base_link_inertial_joint' type="fixed">
    <axis xyz="1 0 0"/>
    <origin xyz="0.000 0.000 0.060" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="base_link_inertial"/>
  </joint>

  <!-- 
    Add wheels to the robot chassis (Pololu Zumo in a very simplified design)
    Call WHEEL MACRO: Creates link + joint vs."base_link" 
  -->
  <xacro:wheel  wheel_prefix="front_left"  
                origin_xyz="${wheel_axis_distance/2}  ${wheel_axis_width/2} ${chassis_height/2}" 
                origin_rpy="0 0 0"/>
  <xacro:wheel   wheel_prefix="front_right" 
                origin_xyz="${wheel_axis_distance/2} -${wheel_axis_width/2} ${chassis_height/2}" 
                origin_rpy="0 0 0"/>
  <xacro:wheel  wheel_prefix="rear_left"   
                origin_xyz="-${wheel_axis_distance/2}  ${wheel_axis_width/2} ${chassis_height/2}" 
                origin_rpy="0 0 0"/>
  <xacro:wheel  wheel_prefix="rear_right"  
                origin_xyz="-${wheel_axis_distance/2} -${wheel_axis_width/2} ${chassis_height/2}" 
                origin_rpy="0 0 0"/>

  <!-- 
    Robot Body.
    1) Visual = mesh + box (as grip)
    2) Collsion = uppe_deck + lower_deck boxes
  -->
  <link name='body_base_link'>
    <pose>0 0 0 0 0 0</pose>

    <visual name='Pet_Mk_IV_body_visual'>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI}"/>
      <geometry>
<!--
      ???????????????????????????????????????????????????????????????????????????
      Works in Gazebo - But NOT Rviz!!!
      http://gazebosim.org/tutorials/?tut=attach_meshes     
        <mesh 
          filename="$(find pet_mk_iv_description)/mesh/pet_mk_iv_body.stl"
          scale="0.001 0.001 0.001" 
        /> 
      ???????????????????????????????????????????????????????????????????????????
-->  
        <mesh 
          filename="package://pet_mk_iv_description/mesh/pet_mk_iv_body.stl"
          scale="0.001 0.001 0.001" 
        />  <!-- Scale .stl file from mm to m -->
      </geometry>
      <material name='brown'/>   <!-- Color in RViz -->
    </visual>

    <visual name='Pet_Mk_IV_body_grip_link_visual'>
      <origin xyz="0 0 ${body_height/2+0.055}" rpy=" 0 0 0"/>
      <geometry>
        <box size= "0.015 0.135 0.070"/>  
      </geometry>
      <material name="green"/>
    </visual>
    
    <collision name='Pet_Mk_IV_body_grip_collision'>
      <origin xyz="0 0 ${body_height/2+0.055}" rpy=" 0 0 0"/>
      <geometry>
        <box size= "0.015 0.135 0.070"/>  <!-- Cube of Robot Grip -->
      </geometry>
    </collision>

    <collision name='Pet_Mk_IV_body_upper_deck_collision'>
      <origin xyz="0 0 ${body_height_upper_deck}" rpy=" 0 0 0"/>
      <geometry>
        <box size= "${body_length} ${body_width} ${body_thicknes_upper_deck}"/>
      </geometry>
      <material name="green"/>
    </collision>

    <collision name='Pet_Mk_IV_body_lower_deck_collision'>
      <origin xyz="0 0 ${body_height_lower_deck}" rpy=" 0 0 0"/>
      <geometry>
        <box size= "${body_length} ${body_width} ${body_thicknes_lower_deck}"/>
      </geometry>
      <material name="green"/>
    </collision>

  </link>

  <joint name='body_base_link_joint' type="fixed">
    <axis xyz="1 0 0"/>${sonar_center_height}
    <origin xyz="0 0 ${chassis_height}" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="body_base_link"/>
  </joint>


  <!-- 
    Call SENSOR MACRO's: Creates link + joint vs."base_link" + Connect to Gazebo-plugin
  -->
  <xacro:RPi_camera sensor_prefix="front" 
                 topic="camera_front"
                 origin_xyz="${body_length/2+0.005} 0.0 0.095"
                 origin_rpy="0 0 0"/>
  
  <xacro:sensor_hc_sr04_sonarRange sensor_prefix="front_middle" 
                 topic="range_sensors/front_middle"
                 origin_xyz="0.095 0.0 ${sonar_center_height}"
                 origin_rpy="0 0 0"/>

  <xacro:sensor_hc_sr04_sonarRange sensor_prefix="front_left" 
                 topic="range_sensors/front_left"
                 origin_xyz="0.077 0.042 ${sonar_center_height}"
                 origin_rpy="0 0 ${PI/4}"/>   <!-- +PI/4 = +45'deg -->

  <xacro:sensor_hc_sr04_sonarRange sensor_prefix="front_right" 
                 topic="range_sensors/front_right"
                 origin_xyz="0.077 -0.042 ${sonar_center_height}"
                 origin_rpy="0 0 -${PI/4}"/>  <!-- -PI/4 = -45'deg -->

  <xacro:sensor_mpu6050_imu sensor_name="imu" 
                  topic="imu"
                  origin_xyz="0.000 0.000 0.085"
                  origin_rpy="0 0 0"/>

  <xacro:sensor_fc_123_lineDetector sensor_prefix="right" 
                  topic="line_sensors/right"
                  origin_xyz="0.050 -0.022 0.002"
                  origin_rpy="0 0 0"/>

  <xacro:sensor_fc_123_lineDetector sensor_prefix="mid" 
                  topic="line_sensors/mid"
                  origin_xyz="0.050 0.000 0.002"
                  origin_rpy="0 0 0"/>

  <xacro:sensor_fc_123_lineDetector sensor_prefix="left" 
                  topic="line_sensors/left"
                  origin_xyz="0.050 0.022 0.002"
                  origin_rpy="0 0 0"/>

  <!-- 
    Call COSMETIC BODY PART MACRO's: Creates link + joint vs."base_link"
  -->
  <xacro:visual_raspberryPi3B_sbc name="raspiKull4" 
                origin_xyz="0.005 -0.005 0.095"
                origin_rpy="0 0 ${PI/2}"/>

</robot>

